# Site settings
title: aman purwar
email: amanpurwar35@gmail.com
url: https://github.com/amanpurwar/amanpurwar.github.io
description: "Hi, You have reached Aman's space"
keywords: "amanpurwar, backend, cpp, developer, computer-science, google, purdue, iit, cs"
skills: "Computer Science Graduate - Software Engineer - Tech Geek"
meta_author: Aman Purwar

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Aman Kumar Purwar
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/aman.purwar.1998/
  - title: stack-overflow
    url: https://stackoverflow.com/users/6386094/aman-purwar
  - title: github
    url: https://github.com/amanpurwar
  - title: linkedin
    url: https://www.linkedin.com/in/aman-purwar-948534103/

# Postal address (add as many lines as necessary)
address:
  - line: 5-D-4, NTPC Colony
  - line: Shaktinagar, India 231222

# Credits content
credits: 'open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
